<?php

class PxlBannerBox_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_banner_box';
    protected $title = 'Case Call Help';
    protected $icon = 'eicon-posts-ticker';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_layout","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"https:\/\/main-street-health.local\/wp-content\/themes\/medicross\/elements\/widgets\/img-layout\/pxl_banner_box\/layout1.jpg"}}}]},{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"title_banner","label":"Title","type":"text"},{"name":"sub_title_number","label":"SubTitle Phone Number","type":"text"},{"name":"phone_number","label":"Phone Number","type":"text"},{"name":"phone_link","label":"Phone Link","type":"url","description":"tel:Phone Number"},{"name":"description","label":"Description","type":"textarea"},{"name":"button_text","label":"Button Text","type":"text"},{"name":"item_link","label":"Item Link","type":"url"}]},{"name":"section_style","label":"General","tab":"style","controls":[{"name":"style","label":"Style","type":"select","options":{"style-1":"Style 1","style-2":"Style 2"},"default":"style-1"},{"name":"p_image","label":"Background Image Box Phone","type":"media"},{"name":"ct_hv-r","label":"Content Hover Space","type":"slider","control_type":"responsive","size_units":["px","%"],"range":{"px":{"min":-300,"max":300}},"selectors":{"{{WRAPPER}} .pxl-banner .hover-content":"transform: translatex({{SIZE}}{{UNIT}});"}},{"name":"color_p","label":"Primary Box Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .top-content , {{WRAPPER}} .pxl-banner .wrap--phone":"background-color: {{VALUE}} !important;","{{WRAPPER}} .pxl-banner .btn":"background-color: {{VALUE}};"}},{"name":"color_s","label":"Secondary Box Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner  .hover-content":"background-color: {{VALUE}} !important;"}},{"name":"color_bdb","label":"Border Box Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner  .hover-content":"border-color: {{VALUE}} !important;"}}]},{"name":"section_style_title","label":"Title Phone","tab":"style","controls":[{"name":"color_tl","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .subtitle-phone":"color: {{VALUE}};"}},{"name":"tile_typography","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-banner .subtitle-phone"}]},{"name":"section_style_phone","label":"Phone","tab":"style","controls":[{"name":"color_phone","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .phone-number":"color: {{VALUE}};"}},{"name":"phone_tp","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-banner .phone-number"}]},{"name":"section_style_des","label":"Description","tab":"style","controls":[{"name":"color_desc","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-banner .desc":"color: {{VALUE}};"}},{"name":"desc_tp","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-banner .desc"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}